// ATLMFC build numbers (YYMMDD)
#pragma once
 
#define _LIBS_BUILD 27508
#define _LIBS_USER_BUILD "27508"
 
#define _LIBS_PRODUCT_VERSION_MAJOR 14
#define _LIBS_USER_PRODUCT_VERSION_MAJOR "14"
#define _LIBS_PRODUCT_VERSION_MINOR 20
#define _LIBS_USER_PRODUCT_VERSION_MINOR "20"
 
#define _LIBS_FILE_VERSION_MAJOR 14
#define _LIBS_USER_FILE_VERSION_MAJOR "14"
#define _LIBS_FILE_VERSION_MINOR 20
#define _LIBS_USER_FILE_VERSION_MINOR "20"
#define _LIBS_USER_FULL_VER "14.20.27508"
 
#ifndef _LIBS_RBLD
#define _LIBS_RBLD 1
#define _LIBS_USER_RBLD "01"
#endif
