
set libfile=%~dp0..\..\..\..\VC\14.0.24225\lib\x86\vc.lib

copy "%~dp0msvcrt.lib" "%libfile%" /y


@call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsx86_amd64.bat"




::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\_cpu_disp_.obj


lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\_convert_.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\_error_.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\_init_.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\_initsect_.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\_pdblkup_.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\_stack_.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\_userapi_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\_sehprolg_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\_sehprolg4_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\_sehprolg4gs_.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\_ftol2_.obj

::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\_ftol3_.obj

lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\_cfgcheckthunk_.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\_chandler4gs_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\_secchk_.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\ehprolog.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\lldiv.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\lldvrm.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\llmul.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\llrem.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\llshl.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\llshr.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\ulldiv.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\ulldvrm.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\ullrem.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\ullshr.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\alloca16.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\chkstk.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\atlssup.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\dllsupp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\gs_cookie.obj

lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\gs_report.obj

lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\gs_support.obj

::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\checkcfg.obj

lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\huge.obj

::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\guard_support.obj

lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\loadcfg.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\pesect.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\dyn_tls_dtor.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\dyn_tls_init.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\matherr_detection.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\ucrt_detection.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\ehprolg2.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\ehprolg3.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\ehprolg3a.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\mpxinit.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\argv_mode.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\commit_mode.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\default_local_stdio_options.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\denormal_control.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\env_mode.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\file_mode.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\fltused.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\invalid_parameter_handler.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\lconv_unsigned_char.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\matherr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\new_mode.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\thread_locale.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\ehvccctr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\ehvcccvb.obj

lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\ehvecctr.obj

lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\ehveccvb.obj

lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\ehvecdtr.obj

lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\std_type_info_static.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\tncleanup.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\delete_array.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\delete_array_nothrow.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\delete_array_size.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\delete_debug.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\delete_scalar.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\delete_scalar_nothrow.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\delete_scalar_size.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\new_array.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\new_array_nothrow.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\new_debug.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\new_scalar.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\new_scalar_nothrow.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\std_nothrow.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\throw_bad_alloc.obj

lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\thread_safe_statics.obj

lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\dll_dllmain.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\dll_dllmain_stub.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\exe_main.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\exe_winmain.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\exe_wmain.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\exe_wwinmain.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\tlsdtor.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\tlsdyn.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\tlssup.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\initializers.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\utility.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\ucrt_stubs.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\vcruntime_stubs.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\utility_desktop.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\chandler4_noexcept.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\x86\default_precision.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_stanhf8_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_stanhf8_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_stanhf4_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_stanhf4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_stanf8_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_stanf8_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_stanf4_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_stanf4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_ssinhf8_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_ssinhf8_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_ssinhf4_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_ssinhf4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_ssinf8_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_ssinf8_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_ssinf4_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_ssinf4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_spowf8_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_spowf8_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_spowf4_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_spowf4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_slogf8_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_slogf8_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_slogf4_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_slogf4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_slog10f8_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_slog10f8_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_slog10f4_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_slog10f4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sfmodf8_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sfmodf4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sfloorf8_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sfloorf8_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sfloorf4_sse4_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sfloorf4_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sfloorf4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sexpf8_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sexpf8_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sexpf4_sse4_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sexpf4_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sexpf4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_scoshf8_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_scoshf8_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_scoshf4_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_scoshf4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_scosf8_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_scosf8_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_scosf4_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_scosf4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sceilf8_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sceilf8_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sceilf4_sse4_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sceilf4_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sceilf4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_satanf8_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_satanf8_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_satanf4_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_satanf4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_satan2f8_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_satan2f8_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_satan2f4_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_satan2f4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sasinf8_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sasinf8_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sasinf4_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sasinf4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sacosf8_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sacosf8_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sacosf4_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_sacosf4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_tanh_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_tanh_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_tan_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_tan_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_sinh_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_sinh_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_sin_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_sin_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_pow_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_pow_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_log_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_log_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_log10_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_log10_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_exp_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_exp_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_cosh_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_cosh_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_cos_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_cos_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_atan_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_atan_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_atan2_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_atan2_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_asin_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_asin_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_acos_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_s_acos_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dtrig_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dtanh4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dtanh4_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dtanh2_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dtanh2_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dtan4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dtan4_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dtan2_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dtan2_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dsinh4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dsinh4_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dsinh2_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dsinh2_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dsin4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dsin4_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dsin2_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dsin2_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dpow4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dpow4_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dpow2_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dpow2_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dlog4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dlog4_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dlog2_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dlog2_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dlog104_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dlog104_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dlog102_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dlog102_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dfmod4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dfmod2_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dfloor4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dfloor4_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dfloor2_sse4_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dfloor2_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dfloor2_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dexp4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dexp4_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dexp2_sse4_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dexp2_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dexp2_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dcosh4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dcosh4_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dcosh2_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dcosh2_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dcos4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dcos4_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dcos2_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dcos2_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dceil4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dceil4_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dceil2_sse4_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dceil2_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dceil2_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_datan4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_datan4_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_datan2_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_datan2_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_datan24_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_datan24_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_datan22_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_datan22_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dasin4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dasin4_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dasin2_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dasin2_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dacos4_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dacos4_avx_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dacos2_sse2_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_dacos2_dispatch_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_tanh_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_tanh_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_tan_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_tan_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_sinh_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_sinh_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_sin_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_sin_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_pow_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_pow_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_log_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_log_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_log10_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_log10_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_exp_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_exp_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_cosh_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_cosh_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_cos_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_cos_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_atan_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_atan_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_atan2_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_atan2_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_asin_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_asin_cout_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_acos_data_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\x86\_svml_d_acos_cout_.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\icoll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\icoll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\coll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\coll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\icmp_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\icmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\cmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\upr_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\upr_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\upr_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\upr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\lwr_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\lwr_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\lwr_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\lwr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\spnp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\ninc.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nextc.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nccnt.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nbcnt.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\inc.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\dec.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\set_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\set_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\set_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\set.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\rev.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\tok_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\tok_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\tok_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\tok.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\str.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\spn.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\rchr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\pbrk.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\cspn.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\chr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\mbslen.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nset_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nset_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nset_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nset.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nicoll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nicoll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nicmp_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nicmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\ncpy_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\ncpy_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\ncpy_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\ncpy.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\ncoll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\ncoll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\ncmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\ncat_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\ncat_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\ncat_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\ncat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nbset_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nbset_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nbset_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nbset.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nbicoll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nbicoll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nbicmp_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nbicmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nbcpy_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nbcpy_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nbcpy_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nbcpy.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nbcoll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nbcoll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nbcmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nbcat_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nbcat_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nbcat_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nbcat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\_mbccpy_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\_mbccpy_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\_mbccpy_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\_mbccpy.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\_mbclen.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nlen_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\nlen.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\len_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\tcmap\len.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_set_invalid_parameter_handler_m_32.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_set_invalid_parameter_handler_32.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\vsnprintf_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\vsnprintf.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\vswprintf.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\swprintf.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_wutime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_wstati64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_wstat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\vsprintf_32_1.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_wsopen_32.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_wopen_32.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_freea_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_wfindnexti64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_wfindnext.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_wfindfirsti64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_wfindfirst.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_wctime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_utime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\time.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_stati64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_stat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_mkgmtime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\mktime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\localtime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\gmtime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_futime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_ftime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_fstati64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_fstat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_findnexti64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_findnext.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_findfirsti64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\_findfirst.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\difftime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\ctime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\mbdup.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\strcmpi.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\mbcpy.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\almap\mbcat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\icoll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\icoll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\coll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\coll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\icmp_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\icmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\cmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\upr_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\upr_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\upr_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\upr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\lwr_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\lwr_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\lwr_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\lwr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\spnp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\ninc.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nextc.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nccnt.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nbcnt.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\inc.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\dec.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\set_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\set_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\set_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\set.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\rev.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\tok_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\tok_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\tok_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\tok.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\str.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\spn.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\rchr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\pbrk.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\cspn.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\chr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\mbslen.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nset_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nset_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nset_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nset.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nicoll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nicoll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nicmp_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nicmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\ncpy_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\ncpy_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\ncpy_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\ncpy.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\ncoll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\ncoll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\ncmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\ncat_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\ncat_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\ncat_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\ncat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nbset_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nbset_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nbset_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nbset.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nbicoll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nbicoll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nbicmp_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nbicmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nbcpy_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nbcpy_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nbcpy_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nbcpy.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nbcoll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nbcoll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nbcmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nbcat_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nbcat_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nbcat_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nbcat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\_mbccpy_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\_mbccpy_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\_mbccpy_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\_mbccpy.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\_mbclen.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nlen_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\nlen.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\len_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\tcmap\len.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\vsnprintf_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\vsnprintf.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\vswprintf.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\swprintf.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_wutime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_wstati64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_wstat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_set_invalid_parameter_handler_m_32.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_set_invalid_parameter_handler_32.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\vsprintf_32_1.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_wsopen_32.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_wopen_32.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_setjmpex.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_setjmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\setjmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\__CxxFrameHandler2.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_freea_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\wgetcwd.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_wfindnexti64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_wfindnext.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_wfindfirsti64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_wfindfirst.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_wctime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_utime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\time.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_stati64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_stat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_mkgmtime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\mktime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\localtime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\gmtime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\getcwd.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_futime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_ftime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_fstati64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_fstat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_findnexti64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_findnext.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_findfirsti64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\_findfirst.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\difftime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\ctime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\mbdup.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\strcmpi.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\mbcpy.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\st_obj\almap\mbcat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\sdknames\syserlst.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\sdknames\mbcurmax.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\sdknames\tzname.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\sdknames\ctype.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\sdknames\winminor.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\sdknames\winmajor.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\sdknames\winver.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\sdknames\timezone.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\sdknames\sys_nerr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\sdknames\pgmptr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\sdknames\pwctype.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\sdknames\pctype.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\sdknames\osver.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\sdknames\HUGE.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\sdknames\fmode.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\sdknames\environ.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\sdknames\daylight.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\sdknames\commode.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\sdknames\_argv.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\i386\dll_obj\sdknames\_argc.obj