set libfile=%~dp0..\..\..\..\VC\14.16.27023\lib\arm\vc.lib

copy "%~dp0msvcrt.lib" "%libfile%" /y

@call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_findfirst.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_findfirsti64.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_findnext.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_findnexti64.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_freea_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_fstat.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_fstati64.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_ftime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_futime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_mkgmtime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_set_invalid_parameter_handler_32.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_set_invalid_parameter_handler_m_32.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_stat.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_stati64.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_utime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_wctime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_wfindfirst.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_wfindfirsti64.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_wfindnext.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_wfindnexti64.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_wopen_32.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_wsopen_32.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_wstat.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_wstati64.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\_wutime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\ctime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\difftime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\gmtime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\localtime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\mbcat.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\mbcpy.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\mbdup.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\mktime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\strcmpi.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\swprintf.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\time.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\vsnprintf.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\vsnprintf_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\vsprintf_32_1.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\almap\vswprintf.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\sdknames\_argc.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\sdknames\_argv.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\sdknames\commode.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\sdknames\ctype.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\sdknames\daylight.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\sdknames\environ.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\sdknames\fmode.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\sdknames\HUGE.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\sdknames\mbcurmax.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\sdknames\osver.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\sdknames\pctype.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\sdknames\pgmptr.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\sdknames\pwctype.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\sdknames\sys_nerr.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\sdknames\syserlst.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\sdknames\timezone.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\sdknames\tzname.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\sdknames\winmajor.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\sdknames\winminor.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\sdknames\winver.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\_mbccpy.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\_mbccpy_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\_mbccpy_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\_mbccpy_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\_mbclen.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\chr.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\cmp.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\coll.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\coll_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\cspn.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\dec.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\icmp.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\icmp_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\icoll.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\icoll_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\inc.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\len.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\len_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\lwr.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\lwr_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\lwr_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\lwr_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\mbslen.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nbcat.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nbcat_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nbcat_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nbcat_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nbcmp.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nbcnt.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nbcoll.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nbcoll_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nbcpy.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nbcpy_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nbcpy_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nbcpy_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nbicmp.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nbicmp_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nbicoll.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nbicoll_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nbset.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nbset_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nbset_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nbset_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\ncat.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\ncat_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\ncat_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\ncat_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nccnt.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\ncmp.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\ncoll.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\ncoll_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\ncpy.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\ncpy_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\ncpy_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\ncpy_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nextc.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nicmp.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nicmp_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nicoll.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nicoll_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\ninc.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nlen.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nlen_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nset.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nset_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nset_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\nset_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\pbrk.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\rchr.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\rev.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\set.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\set_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\set_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\set_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\spn.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\spnp.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\str.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\tok.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\tok_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\tok_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\tok_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\upr.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\upr_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\upr_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\dll_obj\tcmap\upr_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\__CxxFrameHandler2.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_findfirst.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_findfirsti64.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_findnext.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_findnexti64.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_freea_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_fstat.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_fstati64.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_ftime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_futime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_mkgmtime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_set_invalid_parameter_handler_32.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_set_invalid_parameter_handler_m_32.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_setjmp.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_setjmpex.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_stat.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_stati64.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_utime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_wctime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_wfindfirst.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_wfindfirsti64.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_wfindnext.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_wfindnexti64.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_wopen_32.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_wsopen_32.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_wstat.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_wstati64.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\_wutime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\ctime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\difftime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\getcwd.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\gmtime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\localtime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\mbcat.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\mbcpy.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\mbdup.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\mktime.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\setjmp.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\strcmpi.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\swprintf.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\time.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\vsnprintf.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\vsnprintf_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\vsprintf_32_1.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\vswprintf.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\almap\wgetcwd.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\_mbccpy.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\_mbccpy_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\_mbccpy_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\_mbccpy_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\_mbclen.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\chr.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\cmp.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\coll.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\coll_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\cspn.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\dec.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\icmp.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\icmp_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\icoll.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\icoll_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\inc.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\len.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\len_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\lwr.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\lwr_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\lwr_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\lwr_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\mbslen.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nbcat.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nbcat_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nbcat_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nbcat_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nbcmp.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nbcnt.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nbcoll.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nbcoll_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nbcpy.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nbcpy_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nbcpy_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nbcpy_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nbicmp.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nbicmp_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nbicoll.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nbicoll_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nbset.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nbset_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nbset_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nbset_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\ncat.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\ncat_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\ncat_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\ncat_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nccnt.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\ncmp.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\ncoll.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\ncoll_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\ncpy.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\ncpy_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\ncpy_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\ncpy_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nextc.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nicmp.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nicmp_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nicoll.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nicoll_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\ninc.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nlen.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nlen_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nset.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nset_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nset_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\nset_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\pbrk.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\rchr.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\rev.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\set.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\set_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\set_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\set_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\spn.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\spnp.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\str.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\tok.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\tok_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\tok_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\tok_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\upr.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\upr_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\upr_s.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\crt_bld\arm\st_obj\tcmap\upr_s_l.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\argv_mode.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\armsecgs.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\cfgcheckthunk.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\checkcfg.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\chkstk.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\commit_mode.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\convert.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\cpu_disp.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\debugger_jmc.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\default_local_stdio_options.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\delete_array.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\delete_array_align.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\delete_array_align_nothrow.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\delete_array_nothrow.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\delete_array_size.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\delete_array_size_align.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\delete_debug.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\delete_scalar.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\delete_scalar_align.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\delete_scalar_align_nothrow.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\delete_scalar_nothrow.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\delete_scalar_size.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\delete_scalar_size_align.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\denormal_control.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\divide.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\dll_dllmain.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\dll_dllmain_stub.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\dyn_tls_dtor.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\dyn_tls_init.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\ehvccctr.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\ehvcccvb.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\ehvecctr.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\ehveccvb.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\ehvecdtr.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\env_mode.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\error.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\exe_main.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\exe_winmain.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\exe_wmain.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\exe_wwinmain.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\file_mode.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\fltused.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\fptoi64.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\gs_cookie.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\gs_report.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\gs_support.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\gshandler.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\gshandlereh.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\gshandlerseh.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\gshandlerseh_noexcept.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\guard_support.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\helpexcept.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\huge.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\i64tofp.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\init.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\initializers.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\initsect.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\invalid_parameter_handler.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\lconv_unsigned_char.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\loadcfg.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\matherr.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\matherr_detection.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\new_array.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\new_array_align.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\new_array_align_nothrow.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\new_array_nothrow.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\new_debug.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\new_mode.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\new_scalar.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\new_scalar_align.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\new_scalar_align_nothrow.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\new_scalar_nothrow.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\pdblkup.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\pesect.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\rshi64.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\rshui64.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\secpushpop.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\stack.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\std_nothrow.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\std_type_info_static.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\thread_locale.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\thread_safe_statics.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\throw_bad_alloc.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\tlsdtor.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\tlsdyn.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\tlssup.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\tncleanup.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\ucrt_detection.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\ucrt_stubs.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\userapi.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\utility.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\utility_desktop.obj
lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm\vcruntime_stubs.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm\svml_vasin.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm\svml_vatan.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm\svml_vexp.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm\svml_vfmod.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm\svml_vidiv.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm\svml_vlog.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm\svml_vpow.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm\svml_vsin.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm\svml_vsinh.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm\svml_vtan.obj
::lib "%libfile%" /remove:d:\agent\_work\2\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm\svml_vtanh.obj
