setlocal
set libfile=%~dp0..\..\..\..\VC\%CurrentBuildVersion%\lib\arm64\vc.lib

copy "%~dp0msvcrt.lib" "%libfile%" /y

lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_findfirst.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_findfirsti64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_findnext.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_findnexti64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_freea_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_fstat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_fstati64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_ftime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_futime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_mkgmtime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_set_invalid_parameter_handler_32.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_set_invalid_parameter_handler_m_32.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_stat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_stati64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_utime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_wctime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_wfindfirst.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_wfindfirsti64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_wfindnext.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_wfindnexti64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_wopen_32.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_wsopen_32.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_wstat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_wstati64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_wutime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\ctime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\difftime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\gmtime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\localtime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\mbcat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\mbcpy.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\mbdup.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\mktime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\strcmpi.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\swprintf.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\time.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\vsnprintf.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\vsnprintf_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\vsprintf_32_1.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\vswprintf.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\_argc.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\_argv.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\commode.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\ctype.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\daylight.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\environ.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\fmode.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\HUGE.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\mbcurmax.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\osver.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\pctype.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\pgmptr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\pwctype.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\sys_nerr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\syserlst.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\timezone.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\tzname.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\winmajor.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\winminor.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\winver.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\_mbccpy.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\_mbccpy_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\_mbccpy_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\_mbccpy_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\_mbclen.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\chr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\cmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\coll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\coll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\cspn.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\dec.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\icmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\icmp_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\icoll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\icoll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\inc.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\len.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\len_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\lwr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\lwr_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\lwr_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\lwr_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\mbslen.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcat_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcat_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcat_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcnt.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcoll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcoll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcpy.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcpy_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcpy_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcpy_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbicmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbicmp_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbicoll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbicoll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbset.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbset_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbset_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbset_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncat_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncat_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncat_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nccnt.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncoll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncoll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncpy.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncpy_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncpy_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncpy_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nextc.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nicmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nicmp_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nicoll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nicoll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ninc.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nlen.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nlen_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nset.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nset_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nset_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nset_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\pbrk.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\rchr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\rev.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\set.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\set_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\set_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\set_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\spn.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\spnp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\str.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\tok.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\tok_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\tok_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\tok_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\upr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\upr_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\upr_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\upr_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\__CxxFrameHandler2.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_findfirst.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_findfirsti64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_findnext.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_findnexti64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_freea_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_fstat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_fstati64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_ftime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_futime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_mkgmtime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_set_invalid_parameter_handler_64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_set_invalid_parameter_handler_m_64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_setjmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_setjmpex.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_stat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_stati64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_utime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_wctime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_wfindfirst.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_wfindfirsti64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_wfindnext.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_wfindnexti64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_wopen_64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_wsopen_64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_wstat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_wstati64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_wutime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\ctime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\difftime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\getcwd.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\gmtime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\localtime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\mbcat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\mbcpy.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\mbdup.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\mktime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\setjmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\strcmpi.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\swprintf.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\time.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\vsnprintf.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\vsnprintf_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\vswprintf.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\almap\wgetcwd.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\_mbccpy.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\_mbccpy_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\_mbccpy_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\_mbccpy_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\_mbclen.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\chr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\cmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\coll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\coll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\cspn.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\dec.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\icmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\icmp_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\icoll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\icoll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\inc.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\len.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\len_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\lwr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\lwr_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\lwr_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\lwr_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\mbslen.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcat_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcat_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcat_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcnt.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcoll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcoll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcpy.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcpy_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcpy_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcpy_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbicmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbicmp_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbicoll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbicoll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbset.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbset_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbset_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbset_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncat_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncat_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncat_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nccnt.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncoll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncoll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncpy.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncpy_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncpy_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncpy_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nextc.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nicmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nicmp_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nicoll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nicoll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ninc.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nlen.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nlen_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nset.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nset_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nset_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nset_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\pbrk.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\rchr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\rev.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\set.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\set_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\set_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\set_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\spn.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\spnp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\str.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\tok.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\tok_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\tok_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\tok_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\upr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\upr_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\upr_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\upr_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_findfirst.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_findfirsti64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_findnext.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_findnexti64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_freea_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_fstat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_fstati64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_ftime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_futime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_mkgmtime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_set_invalid_parameter_handler_32.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_set_invalid_parameter_handler_m_32.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_stat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_stati64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_utime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_wctime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_wfindfirst.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_wfindfirsti64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_wfindnext.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_wfindnexti64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_wopen_32.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_wsopen_32.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_wstat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_wstati64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\_wutime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\ctime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\difftime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\gmtime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\localtime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\mbcat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\mbcpy.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\mbdup.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\mktime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\strcmpi.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\swprintf.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\time.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\vsnprintf.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\vsnprintf_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\vsprintf_32_1.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\almap\vswprintf.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\sdknames\_argc.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\sdknames\_argv.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\sdknames\commode.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\sdknames\ctype.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\sdknames\daylight.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\sdknames\environ.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\sdknames\fmode.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\sdknames\HUGE.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\sdknames\mbcurmax.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\sdknames\osver.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\sdknames\pctype.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\sdknames\pgmptr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\sdknames\pwctype.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\sdknames\sys_nerr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\sdknames\syserlst.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\sdknames\timezone.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\sdknames\tzname.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\sdknames\winmajor.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\sdknames\winminor.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\sdknames\winver.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\_mbccpy.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\_mbccpy_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\_mbccpy_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\_mbccpy_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\_mbclen.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\chr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\cmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\coll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\coll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\cspn.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\dec.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\icmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\icmp_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\icoll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\icoll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\inc.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\len.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\len_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\lwr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\lwr_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\lwr_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\lwr_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\mbslen.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nbcat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nbcat_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nbcat_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nbcat_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nbcmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nbcnt.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nbcoll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nbcoll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nbcpy.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nbcpy_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nbcpy_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nbcpy_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nbicmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nbicmp_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nbicoll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nbicoll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nbset.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nbset_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nbset_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nbset_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\ncat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\ncat_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\ncat_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\ncat_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nccnt.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\ncmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\ncoll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\ncoll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\ncpy.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\ncpy_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\ncpy_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\ncpy_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nextc.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nicmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nicmp_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nicoll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nicoll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\ninc.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nlen.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nlen_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nset.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nset_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nset_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\nset_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\pbrk.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\rchr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\rev.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\set.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\set_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\set_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\set_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\spn.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\spnp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\str.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\tok.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\tok_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\tok_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\tok_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\upr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\upr_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\upr_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\dll_obj\tcmap\upr_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\__CxxFrameHandler2.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_findfirst.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_findfirsti64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_findnext.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_findnexti64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_freea_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_fstat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_fstati64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_ftime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_futime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_mkgmtime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_set_invalid_parameter_handler_64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_set_invalid_parameter_handler_m_64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_setjmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_setjmpex.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_stat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_stati64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_utime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_wctime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_wfindfirst.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_wfindfirsti64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_wfindnext.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_wfindnexti64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_wopen_64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_wsopen_64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_wstat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_wstati64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\_wutime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\ctime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\difftime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\getcwd.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\gmtime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\localtime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\mbcat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\mbcpy.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\mbdup.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\mktime.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\setjmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\strcmpi.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\swprintf.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\time.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\vsnprintf.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\vsnprintf_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\vswprintf.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\almap\wgetcwd.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\_mbccpy.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\_mbccpy_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\_mbccpy_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\_mbccpy_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\_mbclen.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\chr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\cmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\coll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\coll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\cspn.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\dec.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\icmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\icmp_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\icoll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\icoll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\inc.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\len.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\len_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\lwr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\lwr_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\lwr_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\lwr_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\mbslen.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nbcat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nbcat_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nbcat_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nbcat_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nbcmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nbcnt.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nbcoll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nbcoll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nbcpy.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nbcpy_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nbcpy_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nbcpy_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nbicmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nbicmp_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nbicoll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nbicoll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nbset.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nbset_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nbset_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nbset_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\ncat.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\ncat_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\ncat_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\ncat_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nccnt.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\ncmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\ncoll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\ncoll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\ncpy.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\ncpy_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\ncpy_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\ncpy_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nextc.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nicmp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nicmp_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nicoll.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nicoll_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\ninc.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nlen.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nlen_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nset.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nset_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nset_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\nset_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\pbrk.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\rchr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\rev.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\set.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\set_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\set_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\set_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\spn.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\spnp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\str.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\tok.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\tok_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\tok_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\tok_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\upr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\upr_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\upr_s.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\crt_bld\arm64ec\st_obj\tcmap\upr_s_l.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\argv_mode.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\arm64secgs.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\atomics.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\checkcfg.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\chkstk.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\commit_mode.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\convert.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\cpu_disp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\debugger_jmc.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\default_local_stdio_options.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_array.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_array_align.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_array_align_nothrow.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_array_nothrow.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_array_size.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_array_size_align.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_debug.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_scalar.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_scalar_align.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_scalar_align_nothrow.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_scalar_nothrow.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_scalar_size.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_scalar_size_align.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\denormal_control.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\dll_dllmain.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\dll_dllmain_stub.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\dyn_tls_dtor.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\dyn_tls_init.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\ehvccctr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\ehvcccvb.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\ehvecctr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\ehveccvb.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\ehvecdtr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\env_mode.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\error.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\exe_main.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\exe_winmain.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\exe_wmain.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\exe_wwinmain.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\file_mode.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\fltused.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\gs_cookie.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\gs_report.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\gs_support.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\gshandler.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\gshandlereh.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\gshandlerseh.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\gshandlerseh_noexcept.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\guard_support.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\huge.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\init.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\initializers.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\initsect.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\invalid_parameter_handler.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\lconv_unsigned_char.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\loadcfg.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\matherr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\matherr_detection.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\new_array.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\new_array_align.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\new_array_align_nothrow.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\new_array_nothrow.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\new_debug.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\new_mode.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\new_scalar.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\new_scalar_align.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\new_scalar_align_nothrow.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\new_scalar_nothrow.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\pdblkup.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\pesect.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\rtcmemset.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\secpushpop.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\stack.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\std_nothrow.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\std_type_info_static.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\thread_locale.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\thread_safe_statics.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\throw_bad_alloc.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\tlsdtor.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\tlsdyn.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\tlssup.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\tncleanup.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\ucrt_detection.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\ucrt_stubs.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\userapi.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\utility.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\utility_desktop.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\vcruntime_stubs.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\adjthunk_helper.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\amdsecgs.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\argv_mode.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\atomics.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\cfgcheckthunk.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\cfgcheckthunk_arm64ec.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\checkcfg.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\chkstk_arm64ec.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\chkstk_x64.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\chpev2_support.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\commit_mode.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\convert.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\cpu_disp.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\debugger_jmc.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\default_local_stdio_options.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\delete_array.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\delete_array_align.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\delete_array_align_nothrow.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\delete_array_nothrow.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\delete_array_size.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\delete_array_size_align.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\delete_debug.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\delete_scalar.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\delete_scalar_align.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\delete_scalar_align_nothrow.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\delete_scalar_nothrow.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\delete_scalar_size.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\delete_scalar_size_align.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\denormal_control.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\dll_dllmain.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\dll_dllmain_stub.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\dyn_tls_dtor.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\dyn_tls_init.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\ecsecgs.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\ehvccctr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\ehvcccvb.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\ehvecctr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\ehveccvb.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\ehvecdtr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\env_mode.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\error.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\exe_main.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\exe_winmain.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\exe_wmain.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\exe_wwinmain.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\file_mode.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\fltused.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\gs_cookie.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\gs_report.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\gs_support.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\gshandler_amd64.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\gshandler_arm64ec.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\gshandlereh_amd64.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\gshandlereh_arm64ec.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\gshandlereh4_amd64.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\gshandlerseh_amd64.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\gshandlerseh_arm64ec.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\gshandlerseh_noexcept.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\guard_check_arm64ec.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\guard_dispatch.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\guard_support.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\huge.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\icall_helper_arm64ec.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\init.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\initializers.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\initsect.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\invalid_parameter_handler.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\lconv_unsigned_char.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\loadcfg.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\matherr.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\matherr_detection.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\new_array.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\new_array_align.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\new_array_align_nothrow.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\new_array_nothrow.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\new_debug.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\new_mode.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\new_scalar.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\new_scalar_align.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\new_scalar_align_nothrow.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\new_scalar_nothrow.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\pdblkup.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\pesect.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\rtcmemset.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\secpushpop.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\stack.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\std_nothrow.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\std_type_info_static.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\thread_locale.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\thread_safe_statics.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\throw_bad_alloc.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\tlsdtor.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\tlsdyn.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\tlssup.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\tncleanup.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\ucrt_detection.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\ucrt_stubs.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\userapi.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\utility.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\utility_desktop.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\vcall32_helper.obj
lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64ec\vcruntime_stubs.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\svml_vasin.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\svml_vatan.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\svml_vexp.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\svml_vfmod.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\svml_vidiv.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\svml_vlog.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\svml_vpow.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\svml_vsin.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\svml_vsinh.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\svml_vtan.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\svml_vtanh.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64ec\svml_vasin.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64ec\svml_vatan.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64ec\svml_vexp.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64ec\svml_vfmod.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64ec\svml_vidiv.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64ec\svml_vlog.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64ec\svml_vpow.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64ec\svml_vsin.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64ec\svml_vsinh.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64ec\svml_vtan.obj
::lib "%libfile%" /MACHINE:arm64x /remove:D:\agent\_work\10\s\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64ec\svml_vtanh.obj
