set libfile=%~dp0..\..\..\..\VC\14.14.26428\lib\arm64\vc.lib

copy "%~dp0msvcrt.lib" "%libfile%" /y

@call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsamd64_arm64.bat"

::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\_cpu_disp_.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\_convert_.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\_error_.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\_init_.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\_initsect_.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\_pdblkup_.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\_stack_.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\_userapi_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\_arm64secgs_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\_gshandler_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\_gshandlerseh_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\_gshandlerseh_noexcept_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\secpushpop.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\chkstk.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\rtcmemset.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\gs_cookie.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\gs_report.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\gs_support.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\checkcfg.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\huge.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\guard_support.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\loadcfg.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\pesect.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\dyn_tls_dtor.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\dyn_tls_init.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\matherr_detection.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\ucrt_detection.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\gshandlereh.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\argv_mode.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\commit_mode.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\default_local_stdio_options.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\denormal_control.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\env_mode.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\file_mode.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\fltused.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\invalid_parameter_handler.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\lconv_unsigned_char.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\matherr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\new_mode.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\thread_locale.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\ehvccctr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\ehvcccvb.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\ehvecctr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\ehveccvb.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\ehvecdtr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\std_type_info_static.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\tncleanup.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_array.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_array_align.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_array_align_nothrow.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_array_nothrow.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_array_size.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_array_size_align.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_debug.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_scalar.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_scalar_align.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_scalar_align_nothrow.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_scalar_nothrow.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_scalar_size.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\delete_scalar_size_align.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\new_array.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\new_array_align.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\new_array_align_nothrow.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\new_array_nothrow.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\new_debug.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\new_scalar.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\new_scalar_align.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\new_scalar_align_nothrow.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\new_scalar_nothrow.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\std_nothrow.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\throw_bad_alloc.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\thread_safe_statics.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\dll_dllmain.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\dll_dllmain_stub.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\exe_main.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\exe_winmain.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\exe_wmain.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\exe_wwinmain.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\tlsdtor.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\tlsdyn.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\tlssup.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\initializers.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\utility.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\ucrt_stubs.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\vcruntime_stubs.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\msvcrt.nativeproj_110336922\objr\arm64\utility_desktop.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\_svml_vfmod_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\_svml_vidiv_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\_svml_vtanh_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\_svml_vtan_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\_svml_vsinh_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\_svml_vsin_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\_svml_vpow_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\_svml_vlog_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\_svml_vexp_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\_svml_vatan_.obj
::lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\vmath.nativeproj_726318355\objr\arm64\_svml_vasin_.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\icoll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\icoll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\coll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\coll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\icmp_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\icmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\cmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\upr_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\upr_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\upr_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\upr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\lwr_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\lwr_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\lwr_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\lwr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\spnp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ninc.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nextc.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nccnt.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcnt.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\inc.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\dec.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\set_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\set_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\set_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\set.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\rev.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\tok_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\tok_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\tok_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\tok.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\str.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\spn.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\rchr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\pbrk.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\cspn.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\chr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\mbslen.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nset_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nset_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nset_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nset.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nicoll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nicoll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nicmp_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nicmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncpy_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncpy_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncpy_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncpy.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncoll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncoll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncat_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncat_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncat_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\ncat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbset_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbset_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbset_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbset.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbicoll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbicoll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbicmp_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbicmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcpy_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcpy_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcpy_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcpy.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcoll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcoll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcat_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcat_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcat_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nbcat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\_mbccpy_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\_mbccpy_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\_mbccpy_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\_mbccpy.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\_mbclen.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nlen_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\nlen.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\len_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\tcmap\len.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_set_invalid_parameter_handler_m_32.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_set_invalid_parameter_handler_32.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\vsnprintf_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\vsnprintf.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\vswprintf.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\swprintf.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_wutime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_wstati64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_wstat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\vsprintf_32_1.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_wsopen_32.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_wopen_32.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_freea_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_wfindnexti64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_wfindnext.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_wfindfirsti64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_wfindfirst.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_wctime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_utime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\time.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_stati64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_stat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_mkgmtime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\mktime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\localtime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\gmtime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_futime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_ftime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_fstati64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_fstat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_findnexti64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_findnext.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_findfirsti64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\_findfirst.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\difftime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\ctime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\mbdup.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\strcmpi.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\mbcpy.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\almap\mbcat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\icoll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\icoll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\coll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\coll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\icmp_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\icmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\cmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\upr_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\upr_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\upr_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\upr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\lwr_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\lwr_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\lwr_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\lwr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\spnp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ninc.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nextc.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nccnt.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcnt.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\inc.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\dec.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\set_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\set_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\set_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\set.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\rev.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\tok_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\tok_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\tok_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\tok.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\str.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\spn.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\rchr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\pbrk.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\cspn.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\chr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\mbslen.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nset_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nset_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nset_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nset.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nicoll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nicoll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nicmp_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nicmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncpy_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncpy_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncpy_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncpy.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncoll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncoll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncat_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncat_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncat_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\ncat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbset_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbset_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbset_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbset.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbicoll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbicoll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbicmp_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbicmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcpy_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcpy_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcpy_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcpy.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcoll_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcoll.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcat_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcat_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcat_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nbcat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\_mbccpy_s_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\_mbccpy_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\_mbccpy_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\_mbccpy.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\_mbclen.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nlen_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\nlen.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\len_l.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\tcmap\len.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\vsnprintf_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\vsnprintf.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\vswprintf.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\swprintf.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_wutime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_wstati64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_wstat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_set_invalid_parameter_handler_m_64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_set_invalid_parameter_handler_64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_wsopen_64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_wopen_64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_setjmpex.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_setjmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\setjmp.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\__CxxFrameHandler2.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_freea_s.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\wgetcwd.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_wfindnexti64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_wfindnext.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_wfindfirsti64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_wfindfirst.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_wctime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_utime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\time.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_stati64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_stat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_mkgmtime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\mktime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\localtime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\gmtime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\getcwd.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_futime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_ftime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_fstati64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_fstat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_findnexti64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_findnext.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_findfirsti64.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\_findfirst.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\difftime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\ctime.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\mbdup.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\strcmpi.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\mbcpy.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\st_obj\almap\mbcat.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\syserlst.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\mbcurmax.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\tzname.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\ctype.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\winminor.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\winmajor.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\winver.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\timezone.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\sys_nerr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\pgmptr.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\pwctype.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\pctype.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\osver.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\HUGE.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\fmode.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\environ.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\daylight.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\commode.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\_argv.obj
lib "%libfile%" /remove:f:\binaries\Intermediate\vctools\crt_bld\arm64\dll_obj\sdknames\_argc.obj
