// ATLMFC build numbers (YYMMDD)
#pragma once
 
#define _LIBS_BUILD 28610
#define _LIBS_USER_BUILD "28610"
 
#define _LIBS_PRODUCT_VERSION_MAJOR 14
#define _LIBS_USER_PRODUCT_VERSION_MAJOR "14"
#define _LIBS_PRODUCT_VERSION_MINOR 25
#define _LIBS_USER_PRODUCT_VERSION_MINOR "25"
 
#define _LIBS_FILE_VERSION_MAJOR 14
#define _LIBS_USER_FILE_VERSION_MAJOR "14"
#define _LIBS_FILE_VERSION_MINOR 25
#define _LIBS_USER_FILE_VERSION_MINOR "25"
#define _LIBS_USER_FULL_VER "14.25.28610"
 
#ifndef _LIBS_RBLD
#define _LIBS_RBLD 4
#define _LIBS_USER_RBLD "04"
#endif
