// ATLMFC build numbers (YYMMDD)
#pragma once
 
#define _LIBS_BUILD 23026
#define _LIBS_USER_BUILD "23026"
 
#define _LIBS_PRODUCT_VERSION_MAJOR 14
#define _LIBS_USER_PRODUCT_VERSION_MAJOR "14"
#define _LIBS_PRODUCT_VERSION_MINOR 0
#define _LIBS_USER_PRODUCT_VERSION_MINOR "00"
 
#define _LIBS_FILE_VERSION_MAJOR 14
#define _LIBS_USER_FILE_VERSION_MAJOR "14"
#define _LIBS_FILE_VERSION_MINOR 0
#define _LIBS_USER_FILE_VERSION_MINOR "00"
#define _LIBS_USER_FULL_VER "14.00.23026"
 
#ifndef _LIBS_RBLD
#define _LIBS_RBLD 0
#define _LIBS_USER_RBLD "00"
#endif
